version: '3.9'

volumes:
  pg_data:
  db_data:
  var_lib_data:

networks:
  bwizard:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bwizard
      POSTGRES_USER: bwizard
      POSTGRES_DB: bwizard
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready _u bwizard" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bwizard
#  db:
#    image: mariadb
#    environment:
#      MARIADB_ROOT_PASSWORD: bwizard
#      MARIADB_DATABASE: bwizard
#      MARIADB_USER: bwizard
#      MARIADB_PASSWORD: bwizard
#    healthcheck:
#      test: [ "CMD", "mariadb-admin" ,"ping", "-u", "root", "-pbwizard", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10
#    ports:
#      - 3306:3306
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - bwizard
  wizard:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    environment:
      DB_USER: bwizard
      DB_PASS: bwizard
      DB_HOST: db
      DB_DATABASE: bwizard
    ports:
      - 8080:3000
      - 8099:8099
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - var_lib_data:/var/lib/bwizard
      - ./:/app
    networks:
      - bwizard
