version: '3'

env:
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: "postgresql://bwizard:bwizard@127.0.0.1:5432"

tasks:
  setup:
    cmds:
      - go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - npm install @openapitools/openapi-generator-cli -g
  migrations-create:
    cmd: goose -dir ./migrations create {{.CLI_ARGS}} sql
  migrations-migrate:
    cmd: goose -dir ./migrations up
  migrations-down:
    cmd: goose -dir ./migrations down
  gen-http:
    cmds:
      - oapi-codegen -package wizard -generate types,server,strict-server ./api/openapi/wizard/wizard.yml > ./api/openapi/wizard/wizard.gen.go
      - openapi-generator-cli generate -i ./api/openapi/wizard/wizard.yml -g typescript-angular -o ./web/src/app/api