version: '3'

tasks:
  setup:
    cmds:
      - go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest
  gen-http:
    cmds:
      - oapi-codegen -package wizard -generate types,server ./api/openapi/wizard/wizard.yml > ./api/openapi/wizard/wizard.gen.go