/**
 * Backup Wizard API
 * An API to communicate with the backup wizard daemon
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DeviceKind = 'server' | 'computer' | 'mobile';

export const DeviceKind = {
    Server: 'server' as DeviceKind,
    Computer: 'computer' as DeviceKind,
    Mobile: 'mobile' as DeviceKind
};

