/**
 * Backup Wizard API
 * An API to communicate with the backup wizard daemon
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceKind } from './deviceKind';
import { ProtectionStatus } from './protectionStatus';


export interface Device { 
    id: string;
    name: string;
    kind: DeviceKind;
    protection: ProtectionStatus;
    lastBackup?: string;
    ips: Array<string>;
    agent: string;
}
export namespace Device {
}


