/**
 * Backup Wizard API
 * An API to communicate with the backup wizard daemon
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Weekday = 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';

export const Weekday = {
    Monday: 'monday' as Weekday,
    Tuesday: 'tuesday' as Weekday,
    Wednesday: 'wednesday' as Weekday,
    Thursday: 'thursday' as Weekday,
    Friday: 'friday' as Weekday,
    Saturday: 'saturday' as Weekday,
    Sunday: 'sunday' as Weekday
};

